Traceback (most recent call last):
  File "PyAdaptationGUI.py", line 14, in <module>
  File "scipy\io\__init__.pyc", line 85, in <module>
  File "scipy\io\matlab\__init__.pyc", line 13, in <module>
  File "scipy\io\matlab\mio.pyc", line 13, in <module>
  File "scipy\io\matlab\mio4.pyc", line 11, in <module>
  File "scipy\sparse\__init__.pyc", line 223, in <module>
  File "scipy\sparse\csgraph\__init__.pyc", line 150, in <module>
  File "scipy\sparse\csgraph\_shortest_path.pyc", line 12, in <module>
  File "scipy\sparse\csgraph\_shortest_path.pyc", line 10, in __load
  File "_shortest_path.pyx", line 18, in init scipy.sparse.csgraph._shortest_path (scipy\sparse\csgraph\_shortest_path.c:14869)
ImportError: No module named _validation
Traceback (most recent call last):
  File "PyAdaptationGUI.py", line 27, in <module>
  File "StrideCounter.pyc", line 4, in <module>
ImportError: No module named mTkinter
Traceback (most recent call last):
  File "PyAdaptationGUI.py", line 372, in <module>
  File "Tkinter.pyc", line 1860, in destroy
  File "mtTkinter.pyc", line 97, in __call__
_tkinter.TclError: can't invoke "destroy" command:  application has been destroyed
